/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{html,ts}"],
  safelist: [
    "is-active",
    "is-ok",
    "is-warn",
    "is-over",
    "is-positive",
    "is-negative",
    "is-neutral",
    "is-writeoff",
    "is-closed",
    "is-open",
    "is-expense",
    "is-income",
    "is-subscription",
    "is-fuel",
    "is-exchange",
    "is-debt",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#eef4f8",
        surface: "#ffffff",
        "surface-soft": "#f4f8fb",
        ink: "#15202b",
        muted: "#667085",
        line: "#d8e3ec",
        teal: "#0f766e",
        "teal-soft": "#d9f5ef",
        blue: "#2563eb",
        "blue-soft": "#dbeafe",
        rose: "#e11d48",
        "rose-soft": "#ffe4ea",
        amber: "#b7791f",
        "amber-soft": "#fff3cf",
        fuel: "#c05621",
        "fuel-soft": "#fff1e8",
        violet: "#6d5dfc",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "sans-serif",
        ],
      },
      fontWeight: {
        750: "750",
        820: "820",
        850: "850",
        950: "950",
      },
      borderRadius: {
        app: "8px",
      },
      boxShadow: {
        panel: "0 20px 48px rgba(21, 32, 43, 0.1)",
        metric: "0 12px 28px rgba(21, 32, 43, 0.07)",
        control: "0 8px 18px rgba(21, 32, 43, 0.08)",
        tabs: "0 -18px 40px rgba(21, 32, 43, 0.12)",
      },
    },
  },
};
