import { queryRequired } from "./dom";

export interface AppElements {
  syncStatus: HTMLElement;
  startLine: HTMLElement;
  openSettings: HTMLButtonElement;
  openSettingsSecondary: HTMLButtonElement;
  tabButtons: NodeListOf<HTMLButtonElement>;
  tabPanels: NodeListOf<HTMLElement>;
  dailyRemaining: HTMLElement;
  dailyAccrued: HTMLElement;
  dailySpent: HTMLElement;
  dailyRate: HTMLElement;
  dailyTitle: HTMLElement;
  dailyProgress: HTMLElement;
  daysCount: HTMLElement;
  subsRemaining: HTMLElement;
  subsBudget: HTMLElement;
  subsSpent: HTMLElement;
  subsProgress: HTMLElement;
  accountsSummary: HTMLElement;
  currencyStrip: HTMLElement;
  accountsList: HTMLElement;
  chartSummary: HTMLElement;
  expenseChart: SVGSVGElement;
  chartButtons: NodeListOf<HTMLButtonElement>;
  form: HTMLFormElement;
  normalFields: HTMLElement;
  exchangeFields: HTMLElement;
  fuelOptions: HTMLElement;
  fuelType: HTMLInputElement;
  fuelLiters: HTMLInputElement;
  amount: HTMLInputElement;
  amountLabel: HTMLElement;
  account: HTMLSelectElement;
  entryBudgetAmount: HTMLInputElement;
  budgetEquivalentField: HTMLElement;
  debtOptions: HTMLElement;
  debtReceiptField: HTMLElement;
  debtReceipt: HTMLInputElement;
  debtReceiptName: HTMLElement;
  date: HTMLInputElement;
  detail: HTMLInputElement;
  detailLabel: HTMLElement;
  currencyBadge: HTMLElement;
  formMessage: HTMLElement;
  exchangeFromAccount: HTMLSelectElement;
  exchangeFromAmount: HTMLInputElement;
  exchangeToAccount: HTMLSelectElement;
  exchangeToAmount: HTMLInputElement;
  exchangeDate: HTMLInputElement;
  exchangeDetail: HTMLInputElement;
  exchangeRatePreview: HTMLElement;
  swapExchange: HTMLButtonElement;
  settingsForm: HTMLFormElement;
  settingStartDate: HTMLInputElement;
  settingDaily: HTMLInputElement;
  settingDailyEnabled: HTMLInputElement;
  settingSubscriptions: HTMLInputElement;
  accountName: HTMLInputElement;
  accountKind: HTMLSelectElement;
  accountCurrency: HTMLInputElement;
  accountInitial: HTMLInputElement;
  addAccount: HTMLButtonElement;
  settingsAccountsList: HTMLElement;
  settingsMessage: HTMLElement;
  entriesList: HTMLElement;
  historyPagination: HTMLElement;
  historyPrev: HTMLButtonElement;
  historyNext: HTMLButtonElement;
  historyPageInfo: HTMLElement;
  filterButtons: NodeListOf<HTMLButtonElement>;
  exportButton: HTMLButtonElement;
  importButton: HTMLButtonElement;
  importFile: HTMLInputElement;
  analyticsTotal: HTMLElement;
  analyticsExpenses: HTMLElement;
  analyticsSubscriptions: HTMLElement;
  analyticsFuel: HTMLElement;
  turnoverForm: HTMLFormElement;
  turnoverTitle: HTMLInputElement;
  turnoverTarget: HTMLInputElement;
  turnoverCurrency: HTMLInputElement;
  turnoverPeople: HTMLInputElement;
  turnoverMessage: HTMLElement;
  turnoverList: HTMLElement;
  preferencesForm: HTMLFormElement;
  appLanguage: HTMLSelectElement;
  preferencesMessage: HTMLElement;
  debtModal: HTMLElement;
  closeDebtModal: HTMLButtonElement;
  debtModalTitle: HTMLElement;
  debtModalSummary: HTMLElement;
  debtSettlementHistory: HTMLElement;
  debtSettlementForm: HTMLFormElement;
  debtSettlementRows: HTMLElement;
  debtSettlementAmountLabel: HTMLElement;
  debtSettlementAccountLabel: HTMLElement;
  debtSettlementAmount: HTMLInputElement;
  debtSettlementAccount: HTMLSelectElement;
  addDebtSettlementRow: HTMLButtonElement;
  debtCloseToggle: HTMLInputElement;
  debtSettlementDate: HTMLInputElement;
  debtSettlementNote: HTMLElement;
  debtSettlementMessage: HTMLElement;
}

export function getAppElements(): AppElements {
  return {
    syncStatus: queryRequired("#sync-status"),
    startLine: queryRequired("#start-line"),
    openSettings: queryRequired("#open-settings"),
    openSettingsSecondary: queryRequired("#open-settings-secondary"),
    tabButtons: document.querySelectorAll("[data-tab-target]"),
    tabPanels: document.querySelectorAll("[data-tab-panel]"),
    dailyRemaining: queryRequired("#daily-remaining"),
    dailyAccrued: queryRequired("#daily-accrued"),
    dailySpent: queryRequired("#daily-spent"),
    dailyRate: queryRequired("#daily-rate"),
    dailyTitle: queryRequired("#daily-title"),
    dailyProgress: queryRequired("#daily-progress"),
    daysCount: queryRequired("#days-count"),
    subsRemaining: queryRequired("#subs-remaining"),
    subsBudget: queryRequired("#subs-budget"),
    subsSpent: queryRequired("#subs-spent"),
    subsProgress: queryRequired("#subs-progress"),
    accountsSummary: queryRequired("#accounts-summary"),
    currencyStrip: queryRequired("#currency-strip"),
    accountsList: queryRequired("#accounts-list"),
    chartSummary: queryRequired("#chart-summary"),
    expenseChart: queryRequired("#expense-chart"),
    chartButtons: document.querySelectorAll("[data-chart-range]"),
    form: queryRequired("#entry-form"),
    normalFields: queryRequired("#normal-fields"),
    exchangeFields: queryRequired("#exchange-fields"),
    fuelOptions: queryRequired("#fuel-options"),
    fuelType: queryRequired("#fuel-type"),
    fuelLiters: queryRequired("#fuel-liters"),
    amount: queryRequired("#entry-amount"),
    amountLabel: queryRequired("#amount-label"),
    account: queryRequired("#entry-account"),
    entryBudgetAmount: queryRequired("#entry-budget-amount"),
    budgetEquivalentField: queryRequired("#budget-equivalent-field"),
    debtOptions: queryRequired("#debt-options"),
    debtReceiptField: queryRequired("#debt-receipt-field"),
    debtReceipt: queryRequired("#debt-receipt"),
    debtReceiptName: queryRequired("#debt-receipt-name"),
    date: queryRequired("#entry-date"),
    detail: queryRequired("#entry-detail"),
    detailLabel: queryRequired("#detail-label"),
    currencyBadge: queryRequired("#form-currency-badge"),
    formMessage: queryRequired("#form-message"),
    exchangeFromAccount: queryRequired("#exchange-from-account"),
    exchangeFromAmount: queryRequired("#exchange-from-amount"),
    exchangeToAccount: queryRequired("#exchange-to-account"),
    exchangeToAmount: queryRequired("#exchange-to-amount"),
    exchangeDate: queryRequired("#exchange-date"),
    exchangeDetail: queryRequired("#exchange-detail"),
    exchangeRatePreview: queryRequired("#exchange-rate-preview"),
    swapExchange: queryRequired("#swap-exchange"),
    settingsForm: queryRequired("#settings-form"),
    settingStartDate: queryRequired("#setting-start-date"),
    settingDaily: queryRequired("#setting-daily"),
    settingDailyEnabled: queryRequired("#setting-daily-enabled"),
    settingSubscriptions: queryRequired("#setting-subscriptions"),
    accountName: queryRequired("#account-name"),
    accountKind: queryRequired("#account-kind"),
    accountCurrency: queryRequired("#account-currency"),
    accountInitial: queryRequired("#account-initial"),
    addAccount: queryRequired("#add-account"),
    settingsAccountsList: queryRequired("#settings-accounts-list"),
    settingsMessage: queryRequired("#settings-message"),
    entriesList: queryRequired("#entries-list"),
    historyPagination: queryRequired("#history-pagination"),
    historyPrev: queryRequired("#history-prev"),
    historyNext: queryRequired("#history-next"),
    historyPageInfo: queryRequired("#history-page-info"),
    filterButtons: document.querySelectorAll("[data-filter]"),
    exportButton: queryRequired("#export-data"),
    importButton: queryRequired("#import-data"),
    importFile: queryRequired("#import-file"),
    analyticsTotal: queryRequired("#analytics-total"),
    analyticsExpenses: queryRequired("#analytics-expenses"),
    analyticsSubscriptions: queryRequired("#analytics-subscriptions"),
    analyticsFuel: queryRequired("#analytics-fuel"),
    turnoverForm: queryRequired("#turnover-form"),
    turnoverTitle: queryRequired("#turnover-title"),
    turnoverTarget: queryRequired("#turnover-target"),
    turnoverCurrency: queryRequired("#turnover-currency"),
    turnoverPeople: queryRequired("#turnover-people"),
    turnoverMessage: queryRequired("#turnover-message"),
    turnoverList: queryRequired("#turnover-list"),
    preferencesForm: queryRequired("#preferences-form"),
    appLanguage: queryRequired("#app-language"),
    preferencesMessage: queryRequired("#preferences-message"),
    debtModal: queryRequired("#debt-modal"),
    closeDebtModal: queryRequired("#close-debt-modal"),
    debtModalTitle: queryRequired("#debt-modal-title"),
    debtModalSummary: queryRequired("#debt-modal-summary"),
    debtSettlementHistory: queryRequired("#debt-settlement-history"),
    debtSettlementForm: queryRequired("#debt-settlement-form"),
    debtSettlementRows: queryRequired("#debt-settlement-rows"),
    debtSettlementAmountLabel: queryRequired("#debt-settlement-amount-label"),
    debtSettlementAccountLabel: queryRequired("#debt-settlement-account-label"),
    debtSettlementAmount: queryRequired("#debt-settlement-amount"),
    debtSettlementAccount: queryRequired("#debt-settlement-account"),
    addDebtSettlementRow: queryRequired("#add-debt-settlement-row"),
    debtCloseToggle: queryRequired("#debt-close-toggle"),
    debtSettlementDate: queryRequired("#debt-settlement-date"),
    debtSettlementNote: queryRequired("#debt-settlement-note"),
    debtSettlementMessage: queryRequired("#debt-settlement-message"),
  };
}
